#include <stdlib.h>
#include "hw4.h"

/* This file was automatically generated by add-stubs.sh at
 * Thu, Feb 18, 2016  9:48:30 PM. It creates empty definitions for functions
 * the student did not implement so that their code can be tested. It also
 * modifies their .h file to include any declarations which they should have
 * included.
 */

